FORMAT: 1A
HOST: http://r.com

# Rice
全国にお米を配達するスマホアプリのAPIドキュメントになります。


## ログインAPI [/api/login{?address}{?password}]
### ログイン [POST]
+ Parameters
    + address(required, string) ... email.
    + password(required, string`) ... password.

+ Response 200 (application/json)

        {
          "result": "ok",
          "token": "abcdefghijklmnop",
        }

### ログイン メソッドエラー [GET]
+ Response 405 (application/json)

        {
          "result": "ng"
        }

## バージョンAPI [/api/app_version]

### バージョン確認 [GET]
+ Parameters
    + version(required, string) ... application_version.
    + app(string, `デフォルトアプリケーション名`) ... application_name.
    
+ Response 200 (application/json)

        {
          "result": "ok",
          "froce_update": 1,
          "lasted_app_version": "1.01"
        }




