FORMAT: 1A
HOST: http://r.com

# Rice
全国にお米を配達するスマホアプリのAPIドキュメントになります。


## ログインAPI [/api/login]

### ログイン [POST]

+ Request (application/json)

        {
            username : "test@example.com",
            password : "xxxxxxxx",
        }

+ Response 200 (application/json)

        {
          "result": "ok",
          "token": "abcdefghijklmnop",
        }

### ログイン パラメータエラー [PUT]

+ Request (application/json)

        {
            username : "",
            password : "",
        }

+ Response 200 (application/json)

        {
          "result": "ng",
          "message": "ログイン出来ませんでした",
        }

### ログイン メソッドエラー [GET]
+ Response 405 (application/json)

        {
          "result": "ng"
        }

## バージョンAPI [/api/app_version{?version}{?app_name}]

### バージョン確認 [GET]
+ Parameters
    + version(string) ... application_version.
    + app_name(string) ... application_name.
    
+ Response 200 (application/json)

        {
          "result": "ok",
          "froce_update": 1,
          "lasted_app_version": "1.01"
        }



