FORMAT: 1A
HOST: http://r.com

# Rice
全国にお米を配達するスマホアプリのAPIドキュメントになります。


## ログインAPI [/api/login]

### ログイン [POST]

+ Request (application/json)

        {
            username : "test@example.com",
            password : "xxxxxxxx",
        }

+ Response 200 (application/json)

        {
          "result": "ok",
          "token": "abcdefghijklmnop",
        }

### ログイン パラメータエラー [POST]

+ Request (application/json)

        {
            username : "",
            password : "",
        }

+ Response 200 (application/json)

        {
          "result": "ng",
          "message": "ログイン出来ませんでした",
        }

### ログイン メソッドエラー [GET]
+ Response 405 (application/json)

        {
          "result": "ng"
        }

